language: objective-c
osx_image: xcode7.3

install:
  - bundle install

script:
  - bundle exec rake spec
  - bundle exec rake integration:cocoapods_ios
  - bundle exec rake integration:cocoapods_ios_static
  - bundle exec rake integration:cocoapods_osx
  - bundle exec rake integration:carthage_ios
  - bundle exec rake integration:carthage_osx

after_success:
  - bundle exec rake "coverage:consolidate"
  - bundle exec slather coverage --coveralls
